name: mv-homes
version: '${version}'
main: dev.spozap.mvhomes.MvHomes
api-version: '1.20'
author: Xx_EvilMelon_xX
commands:
  sethome:
    usage: /sethome
    description: Sets an user home
  homes:
    usage: /homes
    description: Displays inventory with current homes